[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
license = "MIT"
repository = "https://github.com/rakaly/jomini"

[workspace.dependencies]
jomini = "0.36"
attohttpc = { version = "0.30.1", features = ["tls-vendored"] }
flate2 = { version = "1.1.5", default-features = false, features = ["zlib-rs"] }
highway = "1.3"
memchr = "2.7"
pdx-fixtures = { path = "crates/pdx-fixtures" }
rawzip = "0.5"
serde = { version = "1.0.195", features = ["derive"] }
thiserror = "2.0.0"

[workspace.metadata.release]
tag-message = "Release {{version}}"
pre-release-commit-message = "Release {{version}}"
consolidate-commits = false

[patch.crates-io]
jomini = { path = "crates/jomini" }

[profile.release]
debug = true

[profile.bench]
debug = true
