[package]
name = "imperator-save"
version = "0.4.2"
authors.workspace = true
edition = "2021"
exclude = ["/assets/*", "/fuzz/*"]
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Ergonomically work with Imperator Rome saves (debug and ironman)"
keywords = ["imperator", "ironman"]
categories = ["parsing"]

[features]
serialize = []

[dependencies]
jomini = { workspace = true, features = ["envelope", "json"] }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pdx-fixtures = { workspace = true }
flate2 = { workspace = true }
