[package]
name = "pdx-cli"
version = "0.1.0"
authors.workspace = true
license.workspace = true
repository.workspace = true
edition = "2024"
publish = false
description = "Development CLI for the game save crates"

[[bin]]
name = "pdx"
path = "src/main.rs"

[dependencies]
ck3save = { path = "../ck3save" }
eu4save = { path = "../eu4save" }
hoi4save = { path = "../hoi4save" }
imperator-save = { path = "../imperator-save" }
jomini = { workspace = true, features = ["envelope", "json"] }
pdx-fixtures = { workspace = true }
vic3save = { path = "../vic3save" }
